# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `auth0_current_user` gem.
# Please instead update this file by running `bin/tapioca gem auth0_current_user`.

# source://auth0_current_user//lib/auth0_current_user/api_secured.rb#8
module ApiSecured
  extend ::ActiveSupport::Concern

  private

  # source://auth0_current_user//lib/auth0_current_user/api_secured.rb#32
  def auth_token; end

  # source://auth0_current_user//lib/auth0_current_user/api_secured.rb#17
  def authenticate_request!; end

  # source://auth0_current_user//lib/auth0_current_user/api_secured.rb#49
  def authenticated_klass; end

  # source://auth0_current_user//lib/auth0_current_user/api_secured.rb#60
  def configuration; end

  # source://auth0_current_user//lib/auth0_current_user/api_secured.rb#45
  def current_user; end

  # source://auth0_current_user//lib/auth0_current_user/api_secured.rb#36
  def get_email(token); end

  # source://auth0_current_user//lib/auth0_current_user/api_secured.rb#26
  def http_token; end

  # source://auth0_current_user//lib/auth0_current_user/api_secured.rb#40
  def set_current_user(token); end
end

# source://auth0_current_user//lib/auth0_current_user/version.rb#1
module Auth0CurrentUser
  class << self
    # @yield [configuration]
    #
    # source://auth0_current_user//lib/auth0_current_user.rb#18
    def config; end

    # Returns the value of attribute configuration.
    #
    # source://auth0_current_user//lib/auth0_current_user.rb#14
    def configuration; end

    # Sets the attribute configuration
    #
    # @param value the value to set the attribute configuration to.
    #
    # source://auth0_current_user//lib/auth0_current_user.rb#11
    def configuration=(_arg0); end
  end
end

# source://auth0_current_user//lib/auth0_current_user/configuration.rb#2
class Auth0CurrentUser::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://auth0_current_user//lib/auth0_current_user/configuration.rb#5
  def initialize; end

  # Returns the value of attribute auth0_audience.
  #
  # source://auth0_current_user//lib/auth0_current_user/configuration.rb#3
  def auth0_audience; end

  # Sets the attribute auth0_audience
  #
  # @param value the value to set the attribute auth0_audience to.
  #
  # source://auth0_current_user//lib/auth0_current_user/configuration.rb#3
  def auth0_audience=(_arg0); end

  # Returns the value of attribute auth0_domain.
  #
  # source://auth0_current_user//lib/auth0_current_user/configuration.rb#3
  def auth0_domain; end

  # Sets the attribute auth0_domain
  #
  # @param value the value to set the attribute auth0_domain to.
  #
  # source://auth0_current_user//lib/auth0_current_user/configuration.rb#3
  def auth0_domain=(_arg0); end

  # Returns the value of attribute authenticated_klass.
  #
  # source://auth0_current_user//lib/auth0_current_user/configuration.rb#3
  def authenticated_klass; end

  # Sets the attribute authenticated_klass
  #
  # @param value the value to set the attribute authenticated_klass to.
  #
  # source://auth0_current_user//lib/auth0_current_user/configuration.rb#3
  def authenticated_klass=(_arg0); end

  # Returns the value of attribute client_id.
  #
  # source://auth0_current_user//lib/auth0_current_user/configuration.rb#3
  def client_id; end

  # Sets the attribute client_id
  #
  # @param value the value to set the attribute client_id to.
  #
  # source://auth0_current_user//lib/auth0_current_user/configuration.rb#3
  def client_id=(_arg0); end
end

# source://auth0_current_user//lib/auth0_current_user.rb#7
class Auth0CurrentUser::Error < ::StandardError; end

# source://auth0_current_user//lib/auth0_current_user/version.rb#2
Auth0CurrentUser::VERSION = T.let(T.unsafe(nil), String)

# source://auth0_current_user//lib/auth0_current_user/web_secured.rb#4
module Auth0CurrentUser::WebSecured
  extend ::ActiveSupport::Concern

  # source://auth0_current_user//lib/auth0_current_user/web_secured.rb#12
  def current_user; end

  private

  # source://auth0_current_user//lib/auth0_current_user/web_secured.rb#18
  def authenticated_klass; end

  # source://auth0_current_user//lib/auth0_current_user/web_secured.rb#43
  def authorization_endpoint; end

  # source://auth0_current_user//lib/auth0_current_user/web_secured.rb#51
  def configuration; end

  # source://auth0_current_user//lib/auth0_current_user/web_secured.rb#35
  def email; end

  # @return [Boolean]
  #
  # source://auth0_current_user//lib/auth0_current_user/web_secured.rb#39
  def logged_in_using_omniauth?; end

  # source://auth0_current_user//lib/auth0_current_user/web_secured.rb#47
  def userinfo; end
end

# source://auth0_current_user//lib/auth0_current_user/json_web_token.rb#8
class JsonWebToken
  class << self
    # source://auth0_current_user//lib/auth0_current_user/json_web_token.rb#41
    def configuration; end

    # source://auth0_current_user//lib/auth0_current_user/json_web_token.rb#37
    def get_claim(token, claim_name); end

    # source://auth0_current_user//lib/auth0_current_user/json_web_token.rb#21
    def jwks_hash; end

    # source://auth0_current_user//lib/auth0_current_user/json_web_token.rb#9
    def verify(token); end
  end
end
